import { Project, Node, SyntaxKind, type SourceFile } from "ts-morph";
import * as fs from "node:fs";
import * as path from "node:path";

export interface Func {
  node: Node;
  id: string;
  label: string;
  recv: string;
  name: string;
  file: string;
  line: number;
  col: number;
  pkg: string; // dir relative to root (posix)
  generated: boolean;
}

/** An outbound interface port: callers depend on it, repo-layer classes implement it. */
export interface Port {
  name: string;
  pkg: string;
  file: string;
  line: number;
  col: number;
  implMethods: Node[];
  callers: Node[];
}

export interface Result {
  module: string;
  root: string;
  funcs: Map<Node, Func>;
  callEdges: Array<{ from: Node; to: Node }>;
  ports: Port[];
  /** Resolve a handler expression (route argument) to a project Func node. */
  resolveFunc(expr: Node): Node | undefined;
  sourceFiles: SourceFile[];
}

export function load(root: string): Result {
  root = path.resolve(root);
  const tsconfig = path.join(root, "tsconfig.json");
  let project: Project;
  if (fs.existsSync(tsconfig)) {
    project = new Project({ tsConfigFilePath: tsconfig, skipAddingFilesFromTsConfig: false });
  } else {
    project = new Project({ compilerOptions: { allowJs: false, strict: false } });
    project.addSourceFilesAtPaths([path.join(root, "**/*.ts"), "!**/node_modules/**", "!**/*.d.ts"]);
  }
  const sfs = project.getSourceFiles().filter(
    (sf) => !sf.getFilePath().includes("node_modules") && !sf.isDeclarationFile(),
  );

  const module = path.basename(root);
  const funcs = new Map<Node, Func>();
  const byDecl = new Map<Node, Func>();
  const usedIds = new Set<string>();

  const relPkg = (sf: SourceFile) => {
    // Classify by the file path (without extension); TS layers by file name
    // (controller.ts) as often as by folder.
    const rel = path.relative(root, sf.getFilePath()).split(path.sep).join("/");
    return rel.replace(/\.tsx?$/, "");
  };
  const isGen = (sf: SourceFile) => {
    const t = sf.getFullText().slice(0, 400);
    return /\/\/\s*Code generated .* DO NOT EDIT\.|@generated|<auto-generated>/.test(t) || /\.gen\.ts$|\.generated\.ts$/.test(sf.getFilePath());
  };

  const add = (node: Node, recv: string, name: string, sf: SourceFile) => {
    if (!name) return;
    const start = node.getStart();
    const { line, column } = sf.getLineAndColumnAtPos(start);
    const pkg = relPkg(sf);
    const display = recv ? `(${recv}).${name}` : name;
    let id = `${pkg}.${display}`;
    while (usedIds.has(id)) id += "'";
    usedIds.add(id);
    const f: Func = { node, id, label: display, recv, name, file: sf.getFilePath(), line, col: column, pkg, generated: isGen(sf) };
    funcs.set(node, f);
    byDecl.set(node, f);
  };

  for (const sf of sfs) {
    for (const fn of sf.getFunctions()) add(fn, "", fn.getName() ?? "", sf);
    for (const cls of sf.getClasses()) {
      const recv = cls.getName() ?? "";
      for (const m of cls.getMethods()) add(m, recv, m.getName(), sf);
    }
    for (const v of sf.getVariableDeclarations()) {
      const init = v.getInitializer();
      if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) add(init, "", v.getName(), sf);
    }
  }

  // interface method -> implementer method nodes (CHA-ish, name based)
  const impls = new Map<string, Node[]>();
  const ifaceMethods = new Map<string, Set<string>>();
  const ifaceDecl = new Map<string, import("ts-morph").InterfaceDeclaration>();
  const portImpls = new Map<string, Node[]>();
  const portCallers = new Map<string, Set<Node>>();
  for (const sf of sfs) {
    for (const iface of sf.getInterfaces()) {
      const set = new Set<string>();
      for (const m of iface.getMethods()) set.add(m.getName());
      ifaceMethods.set(iface.getName(), set);
      ifaceDecl.set(iface.getName(), iface);
    }
  }
  for (const sf of sfs) {
    for (const cls of sf.getClasses()) {
      const ifaceNames = cls.getImplements().map((e) => e.getExpression().getText());
      for (const ifn of ifaceNames) {
        const methods = ifaceMethods.get(ifn);
        if (!methods) continue;
        for (const m of cls.getMethods()) {
          if (methods.has(m.getName())) {
            const key = `${ifn}.${m.getName()}`;
            (impls.get(key) ?? impls.set(key, []).get(key)!).push(m);
            (portImpls.get(ifn) ?? portImpls.set(ifn, []).get(ifn)!).push(m);
          }
        }
      }
    }
  }

  const declToNodes = (decl: Node): Node[] => {
    if (byDecl.has(decl)) return [decl];
    // interface method signature -> implementers
    if (Node.isMethodSignature(decl)) {
      const iface = decl.getParent();
      if (iface && Node.isInterfaceDeclaration(iface)) {
        return impls.get(`${iface.getName()}.${decl.getName()}`) ?? [];
      }
    }
    return [];
  };

  const resolveExpr = (expr: Node): Node[] => {
    const sym = expr.getSymbol();
    const decls = sym?.getDeclarations() ?? [];
    const out: Node[] = [];
    for (const d of decls) {
      // arrow const: the variable's initializer is our node
      if (Node.isVariableDeclaration(d)) {
        const init = d.getInitializer();
        if (init && byDecl.has(init)) { out.push(init); continue; }
      }
      out.push(...declToNodes(d));
    }
    return out;
  };

  // call graph
  const callEdges: Array<{ from: Node; to: Node }> = [];
  const seen = new Set<string>();
  for (const [fnNode, f] of funcs) {
    if (!Node.isFunctionDeclaration(fnNode) && !Node.isMethodDeclaration(fnNode) && !Node.isArrowFunction(fnNode) && !Node.isFunctionExpression(fnNode)) continue;
    const body = (fnNode as any).getBody?.();
    if (!body) continue;
    for (const call of body.getDescendantsOfKind(SyntaxKind.CallExpression)) {
      const csym = call.getExpression().getSymbol();
      for (const d of csym?.getDeclarations() ?? []) {
        if (Node.isMethodSignature(d)) {
          const ifc = d.getParent();
          if (ifc && Node.isInterfaceDeclaration(ifc) && portImpls.has(ifc.getName()))
            (portCallers.get(ifc.getName()) ?? portCallers.set(ifc.getName(), new Set()).get(ifc.getName())!).add(fnNode);
        }
      }
      for (const callee of resolveExpr(call.getExpression())) {
        if (callee === fnNode) continue;
        const k = f.id + "->" + (byDecl.get(callee)?.id ?? "");
        if (seen.has(k)) continue;
        seen.add(k);
        callEdges.push({ from: fnNode, to: callee });
      }
    }
  }

  const resolveFunc = (expr: Node): Node | undefined => resolveExpr(expr)[0];

  // outbound interface ports: an interface with implementers and ≥1 caller
  const ports: Port[] = [];
  for (const [name, implNodes] of portImpls) {
    const iface = ifaceDecl.get(name);
    if (!iface) continue;
    const sf = iface.getSourceFile();
    const { line, column } = sf.getLineAndColumnAtPos(iface.getNameNode().getStart());
    ports.push({
      name,
      pkg: relPkg(sf),
      file: sf.getFilePath(),
      line,
      col: column,
      implMethods: [...new Set(implNodes)],
      callers: [...(portCallers.get(name) ?? [])],
    });
  }

  // drop generated funcs from the func set (but keep for route resolution? routes resolve to impl which is non-generated)
  for (const [n, f] of [...funcs]) if (f.generated) funcs.delete(n);

  return { module, root, funcs, callEdges, ports, resolveFunc, sourceFiles: sfs };
}
